language: minimal

services:
  - docker

install:
  - docker pull jjmerelo/raku-test

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install libgtk-3-dev node.js npm

script: docker run -t --user root --entrypoint="/bin/sh" \
  -v /home/richard/development/raku-pod-render:/test jjmerelo/raku-test \
  -c "zef install --deps-only . && prove6 --lib"

